defaults:
- data: zarr
- dataloader: native_grid
- diagnostics: eval_rollout
- hardware: example
- graph: hierarchical_3level
- model: graphtransformer
- training: default
- _self_


### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
# hardware:
#   num_gpus_per_node: 1

diagnostics:
  plot:
    enabled: False
hardware:
  files:
    dataset: ???
    graph: ???
model:
  num_channels: 128
  model:
    __target__: anemoi.models.models.AnemoiModelEncHierProcDec
  process_hierarchy_levels: True
dataloader:
  limit_batches:
    training: 100
    validation: 100
training:
  max_epochs: 5
