version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: training/docs/conf.py

python:
   install:
    - method: pip
      path: training/
      extra_requirements:
        - docs
